# Generated by Django 5.2.5 on 2025-08-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.zone')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
                'unique_together': {('item', 'zone')},
            },
        ),
    ]
