# Generated by Django 5.2.5 on 2025-08-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(help_text='The amount of stock being moved.'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(help_text='Name of the warehouse zone', max_length=100, unique=True),
        ),
    ]
